services:
  empresa123-service:
    build:
      context: .
      dockerfile: empresa123-service/Dockerfile
    container_name: empresa123-service
    ports:
      - "8081:8081"
    networks:
      - integracion-net

  empresaabc-service:
    build:
      context: .
      dockerfile: empresaabc-service/Dockerfile
    container_name: empresaabc-service
    ports:
      - "8087:8087"
    networks:
      - integracion-net

  integration-service:
    build:
      context: .
      dockerfile: integration-service/Dockerfile
    container_name: integration-service
    ports:
      - "8089:8089"
    environment:
      EMPRESA123_BASE_URL: http://empresa123-service:8081
      EMPRESAABC_BASE_URL: http://empresaabc-service:8087
    depends_on:
      - empresa123-service
      - empresaabc-service
    networks:
      - integracion-net

  frontend-clientes:
    build:
      context: ./frontend-clientes
      dockerfile: Dockerfile
    container_name: frontend-clientes
    ports:
      - "5173:80"
    depends_on:
      - integration-service
    networks:
      - integracion-net

networks:
  integracion-net:
    driver: bridge
